image: ritproject/cli:docker
services:
  - docker:dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - test
  - update project images
  - update production images
  - deploy
before_script:
  - rit --log on_error config tunnel add repo https://github.com/altjohndev/fabiommendes-covid-19-tunnel --name tunnel
  - rit --log on_error config tunnel default set tunnel

# Stage: test

test:
  stage: test
  variables:
    BUILD_TYPE: recursive
  script:
    - rit --log on_error tunnel --input disabled run calculator development build
    - rit --log on_error tunnel --input disabled run calculator development test up
    - rit --log on_error tunnel --input disabled run calculator development test sync
    - rit --log on_error tunnel --input disabled run calculator development test all
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--skip-test/
  tags:
    - docker

# Stage: update project images

.update_project_image: &update_project_image
  stage: update project images
  script:
    - rit --log on_error tunnel --input disabled run calculator $CONTEXT build
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run calculator $CONTEXT push
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /--update-project-images/
    refs:
      - /^master$/
  tags:
    - docker

update development image:
  <<: *update_project_image
  variables:
    CONTEXT: development

update production image:
  <<: *update_project_image
  variables:
    CONTEXT: production

# Stage: update production images

update production image:
  stage: update production images
  variables:
    BUILD_TYPE: recursive
    IMAGE_TAG: production
  script:
    - rit --log on_error tunnel --input disabled run calculator production build
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - rit --log on_error tunnel --input disabled run calculator production push
  only:
    - tags
  tags:
    - docker

# Deploy

deploy:
  stage: deploy
  environment:
    name: production
  script:
    - rit --log on_error tunnel --input disabled run calculator production deploy up
    - rit --log on_error tunnel --input disabled run calculator production deploy sync
    - rit --log on_error tunnel --input disabled run calculator production deploy playbook
  only:
    - tags
  tags:
    - docker
